.PHONY: run_fuzz_tests clean run_test_gui_new_match_highlight run_gui_crash_test run_test_dynamic_threshold run_test_roaming_range_enforcement run_test_amanda_carrie_bug run_test_populate_bad_match run_test_full_session_replay run_test_export_stats run_match_history_snapshots run_test_competitive_variety_settings run_test_competitive_variety_slider run_test_competitive_variety_repetition run_test_competitive_variety_requirements run_test_show_rank_button run_test_slider_reevaluation run_test_variety_slider run_test_court_sliding run_test_court_slide_with_historic_load run_test_court_slide_gui_state_reset run_test_first_bye_feature run_test_first_bye_bug_fixes run_test_first_bye_15_players_bug run_test_first_bye_validation_fix run_test_team_balancing_bug run_test_balance_analysis run_test_enhanced_manual_match run_test_balance_bug_reproduction run_test_constraints_debug run_test_scoring_balance run_test_automatic_vs_manual run_test_determinism_fix run_test_first_match_randomization run_test_court_filling_bug test_time_manager test_wait_time_resumption test_realistic_session_resumption test_match_duration_resumption test_complete_session_resumption

run_test_gui_new_match_highlight:
	python3 python/test_gui_new_match_highlight.py

run_fuzz_tests:
	python3 test_competitive_variety_fuzzing.py

run_test_competitive_variety_settings:
	python3 test_competitive_variety_settings.py

run_test_competitive_variety_slider:
	python3 test_competitive_variety_slider.py

run_test_competitive_variety_repetition:
	python3 test_competitive_variety_repetition.py

run_test_competitive_variety_requirements:
	python3 test_competitive_variety_requirements.py

run_test_show_rank_button:
	python3 test_show_rank_button.py

run_test_slider_reevaluation:
	python3 test_slider_reevaluation.py

run_test_variety_slider:
	python3 test_variety_slider.py

run_test_court_sliding:
	python3 test_court_sliding.py

run_test_court_slide_with_historic_load:
	python3 test_court_slide_with_historic_load.py

run_test_court_slide_gui_state_reset:
	python3 test_court_slide_gui_state_reset.py

run_test_first_bye_feature:
	python3 test_first_bye_feature.py

run_test_first_bye_bug_fixes:
	python3 test_first_bye_bug_fixes.py

run_test_first_bye_15_players_bug:
	python3 test_first_bye_15_players_bug.py

run_test_first_bye_validation_fix:
	python3 test_first_bye_validation_fix.py

run_test_team_balancing_bug:
	python3 test_team_balancing_bug.py

run_player_removal_persistence_test:
	python3 test_player_removal_persistence.py

run_test_back_to_back_partner_bug:
	python3 test_back_to_back_partner_bug.py

run_test_partner_repetition_8_players:
	python3 test_partner_repetition_8_players.py

run_test_opponent_repetition_8_players:
	python3 test_opponent_repetition_8_players.py

run_test_direct_history_check:
	python3 test_direct_history_check.py

run_test_priority_queueing:
	python3 test_priority_queueing.py

run_test_per_player_repetition:
	python3 test_per_player_repetition.py

run_test_dense_constraints:
	python3 test_dense_constraints.py

run_test_bracket_restrictions:
	python3 test_bracket_restrictions.py

run_test_roaming_range:
	python3 test_roaming_range.py

run_test_roundrobin_strictness:
	python3 test_roundrobin_strictness.py

run_test_repro_roundrobin_repetition:
	python3 test_repro_roundrobin_repetition.py

run_test_dynamic_threshold:
	python3 test_dynamic_threshold.py

run_test_roaming_range_enforcement:
	python3 test_roaming_range_enforcement.py

run_test_amanda_carrie_bug:
	python3 test_amanda_carrie_bug.py

run_test_populate_bad_match:
	python3 test_populate_bad_match.py

run_test_full_session_replay:
	python3 test_full_session_replay.py

run_test_audio_announcement:
	python3 test_audio_announcement.py

run_test_manual_announcement:
	python3 test_manual_announcement.py

run_test_export_stats:
	python3 test_export_stats.py

run_match_history_snapshots:
	python3 test_match_history_snapshots.py

test_wait_priority:
	python3 test_wait_priority_system.py

test_wait_priority_integration:
	python3 test_wait_priority_integration.py

run_test_balance_analysis:
	python3 test_balance_analysis.py

run_test_enhanced_manual_match:
	python3 test_enhanced_manual_match.py

run_test_balance_bug_reproduction:
	python3 test_balance_bug_reproduction.py

run_test_constraints_debug:
	python3 test_constraints_debug.py

run_test_scoring_balance:
	python3 test_scoring_balance.py

run_test_automatic_vs_manual:
	python3 test_automatic_vs_manual.py

run_test_determinism_fix:
	python3 test_determinism_fix.py

run_test_first_match_randomization:
	python3 test_first_match_randomization.py

run_test_court_filling_bug:
	python3 test_court_filling_bug.py

test_time_manager:
	python3 test_time_manager.py

test_wait_time_resumption:
	python3 test_wait_time_resumption.py

test_realistic_session_resumption:
	python3 test_realistic_session_resumption.py

test_match_duration_resumption:
	python3 test_match_duration_resumption.py

test_complete_session_resumption:
	python3 test_complete_session_resumption.py

test_court_layout_visual:
	python3 test_court_layout_visual.py

test_font_auto_sizing:
	python3 test_font_auto_sizing.py

test_court_name_persistence:
	python3 test_court_name_persistence.py

test_court_integration:
	python3 test_court_integration.py

test_adaptive_matchmaking:
	python3 test_adaptive_matchmaking.py

test_dynamic_thresholds:
	python3 test_dynamic_thresholds.py

clean:
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete
